### ISSUE TITLE
setParams documentation lies: sets POST params not Query params

### ISSUE THREAD

**Issue by robertmassaioli** [markhibberd/network-api-support#5]
If you look at the setParams method you can see:

    -- | Set request query parameters.
    setParams :: [(B.ByteString, B.ByteString)] -> RequestTransformer
    setParams params = Endo $ urlEncodedBody params

Which claims that it sets the requests query params. But this is a lie. It really uses urlEncodedBody which is actually changes the request to be a POST request and puts the params in the request body. You should update the documentation to match the functionality and add a new function:

    -- | Set request query parameters.
    setQueryParams :: [(B.ByteString, Maybe B.ByteString)] -> RequestTransformer
    setQueryParams params = Endo $ setQueryString params

That would solve this problem.

**Comment by markhibberd** [comment]
Fixed by #7.
