### ISSUE TITLE
No instance of Applicative for JsonResult. Breaks with latest GHC base library.

### ISSUE THREAD

**Issue by robertmassaioli** [markhibberd/network-api-support#6]
I get the following error when I attempt to compile this library with the latest base:

    Downloading the latest package list from hackage.haskell.org
    Resolving dependencies...
    Configuring network-api-support-0.1.0...
    Building network-api-support-0.1.0...
    Preprocessing library network-api-support-0.1.0...
    [1 of 4] Compiling Network.Api.Support.Response ( src/Network/Api/Support/Response.hs, dist/dist-sandbox-43829a39/build/Network/Api/Support/Response.o )
    
    src/Network/Api/Support/Response.hs:31:10:
        No instance for (Applicative JsonResult)
          arising from the superclasses of an instance declaration
        In the instance declaration for ‘Monad JsonResult’
    Failed to install network-api-support-0.1.0
    cabal: Error: some packages failed to install:
    atlassian-connect-core-0.5.0.1 depends on network-api-support-0.1.0 which
    failed to install.
    network-api-support-0.1.0 failed during the building phase. The exception was:
    ExitFailure 1

I believe this is because Monad now depends on Applicative in the latest Haskell. This needs to be fixed and a new version of the library released. Cheers.

**Comment by markhibberd** [comment]
Thanks. There also needs to be an extra import for `Control.Applicative` to support ghc < 7.10, if you get a chance add it that would be great (https://travis-ci.org/markhibberd/network-api-support/builds/59656186). Otherwise, I will try to get to it tomorrow.

**Comment by robertmassaioli** [comment]
Done in the previous changeset. :) Could not let it stand. All I need you to do is build, approve, merge and release. Thankyou!

**Comment by robertmassaioli** [comment]
The build went green: https://travis-ci.org/markhibberd/network-api-support/builds/59682642

So this looks good to me.

**Comment by robertmassaioli** [comment]
Note: I have renamed an existing API method call so I suggest releasing this as version 0.2.0. Hopefully you agree. :)

**Comment by markhibberd** [comment]
Fixed by #7.
